# coding: utf-8
"""Generate include/Falcata/c_api_compat.h from include/Falcata/c_api.h.

Falcata's exported C API is FLC_*. This emits inline LGBM_* forwarders so
consumers written against the pre-rename names keep compiling. Run after any
change to the exported C API:

    python .ci/gen-c-api-compat.py
"""

import re
from pathlib import Path

REPO = Path(__file__).absolute().parent.parent
C_API = REPO / "include" / "Falcata" / "c_api.h"
OUT = REPO / "include" / "Falcata" / "c_api_compat.h"

HEADER = """/*!
 * Copyright (c) 2026 Falcata contributors. All rights reserved.
 * Licensed under the MIT License. See LICENSE file in the project root for license information.
 */
#ifndef FALCATA_C_API_COMPAT_H_
#define FALCATA_C_API_COMPAT_H_

/*!
 * \\brief Backwards-compatibility aliases for the historical ``LGBM_*`` C API.
 *
 * Falcata's exported C API is ``FLC_*``. This header keeps the pre-rename
 * ``LGBM_*`` spellings working as inline forwarders (zero runtime cost, no
 * extra exported symbols) so language bindings and externally linked
 * consumers written against the old names keep compiling.
 *
 * This is the ONLY place ``LGBM_`` appears in the implementation. It can be
 * deleted whenever breaking those consumers is acceptable; nothing inside
 * Falcata calls these.
 *
 * Auto-generated by .ci/gen-c-api-compat.py -- do not edit by hand.
 */

#include <Falcata/c_api.h>

"""


def arg_names(args):
    """Parameter names of a C declaration's argument list, in order."""
    names = []
    depth = 0
    current = ""
    # split on top-level commas only (function-pointer args contain commas)
    for ch in args:
        if ch in "(<[":
            depth += 1
        elif ch in ")>]":
            depth -= 1
        if ch == "," and depth == 0:
            names.append(current)
            current = ""
        else:
            current += ch
    names.append(current)

    out = []
    for a in names:
        a = " ".join(a.split())
        if not a or a == "void":
            continue
        # function pointer: void (*callback)(const char*) -> callback
        fp = re.search(r"\(\s*\*\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)", a)
        if fp:
            out.append(fp.group(1))
            continue
        a = re.sub(r"\[\s*\]", "", a)
        idents = re.findall(r"[A-Za-z_][A-Za-z0-9_]*", a)
        if idents:
            out.append(idents[-1])
    return out


def main():
    hdr = C_API.read_text()
    decls = re.findall(
        r"FALCATA_C_EXPORT\s+([A-Za-z_][A-Za-z0-9_ \*]*?)\s+(FLC_[A-Za-z0-9_]+)\s*\(([^;]*?)\);",
        hdr,
        re.S,
    )
    lines = []
    for ret, name, args in decls:
        ret = " ".join(ret.split())
        compact_args = " ".join(args.split())
        old = "LGBM_" + name[len("FLC_"):]
        call = f"{name}({', '.join(arg_names(args))})"
        ret_kw = "" if ret == "void" else "return "
        lines.append(f"inline {ret} {old}({compact_args}) {{ {ret_kw}{call}; }}")

    OUT.write_text(HEADER + "\n".join(lines) + "\n\n#endif  /* FALCATA_C_API_COMPAT_H_ */\n")
    print(f"{OUT.relative_to(REPO)}: {len(lines)} aliases")


if __name__ == "__main__":
    main()
