ARG R_VERSION=latest
FROM rocker/verse:${R_VERSION}

COPY . /src/Falcata

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libomp-dev && \
    cd /src/Falcata && \
    sh build-cran-package.sh --no-build-vignettes && \
    R CMD INSTALL ./falcata_*.tar.gz && \
    cd / && \
    rm -rf /src/Falcata
