/*!
 * Copyright (c) 2026 Falcata contributors. All rights reserved.
 * Licensed under the MIT License. See LICENSE file in the project root for license information.
 */
#ifndef FALCATA_C_API_COMPAT_H_
#define FALCATA_C_API_COMPAT_H_

/*!
 * \brief Backwards-compatibility aliases for the historical ``LGBM_*`` C API.
 *
 * Falcata's exported C API is ``FLC_*``. This header keeps the pre-rename
 * ``LGBM_*`` spellings working as inline forwarders (zero runtime cost, no
 * extra exported symbols) so language bindings and externally linked
 * consumers written against the old names keep compiling.
 *
 * This is the ONLY place ``LGBM_`` appears in the implementation. It can be
 * deleted whenever breaking those consumers is acceptable; nothing inside
 * Falcata calls these.
 *
 * Auto-generated by .ci/gen-c-api-compat.py -- do not edit by hand.
 */

#include <Falcata/c_api.h>

inline const char* LGBM_GetLastError() { return FLC_GetLastError(); }
inline int LGBM_DumpParamAliases(int64_t buffer_len, int64_t* out_len, char* out_str) { return FLC_DumpParamAliases(buffer_len, out_len, out_str); }
inline int LGBM_RegisterLogCallback(void (*callback)(const char*)) { return FLC_RegisterLogCallback(callback); }
inline int LGBM_GetSampleCount(int32_t num_total_row, const char* parameters, int* out) { return FLC_GetSampleCount(num_total_row, parameters, out); }
inline int LGBM_SampleIndices(int32_t num_total_row, const char* parameters, void* out, int32_t* out_len) { return FLC_SampleIndices(num_total_row, parameters, out, out_len); }
inline int LGBM_ByteBufferGetAt(ByteBufferHandle handle, int32_t index, uint8_t* out_val) { return FLC_ByteBufferGetAt(handle, index, out_val); }
inline int LGBM_ByteBufferFree(ByteBufferHandle handle) { return FLC_ByteBufferFree(handle); }
inline int LGBM_DatasetCreateFromFile(const char* filename, const char* parameters, const DatasetHandle reference, DatasetHandle* out) { return FLC_DatasetCreateFromFile(filename, parameters, reference, out); }
inline int LGBM_DatasetCreateFromSampledColumn(double** sample_data, int** sample_indices, int32_t ncol, const int* num_per_col, int32_t num_sample_row, int32_t num_local_row, int64_t num_dist_row, const char* parameters, DatasetHandle* out) { return FLC_DatasetCreateFromSampledColumn(sample_data, sample_indices, ncol, num_per_col, num_sample_row, num_local_row, num_dist_row, parameters, out); }
inline int LGBM_DatasetCreateByReference(const DatasetHandle reference, int64_t num_total_row, DatasetHandle* out) { return FLC_DatasetCreateByReference(reference, num_total_row, out); }
inline int LGBM_DatasetInitStreaming(DatasetHandle dataset, int32_t has_weights, int32_t has_init_scores, int32_t has_queries, int32_t nclasses, int32_t nthreads, int32_t omp_max_threads) { return FLC_DatasetInitStreaming(dataset, has_weights, has_init_scores, has_queries, nclasses, nthreads, omp_max_threads); }
inline int LGBM_DatasetCreateFromSerializedReference(const void* ref_buffer, int32_t ref_buffer_size, int64_t num_row, int32_t num_classes, const char* parameters, DatasetHandle* out) { return FLC_DatasetCreateFromSerializedReference(ref_buffer, ref_buffer_size, num_row, num_classes, parameters, out); }
inline int LGBM_DatasetPushRows(DatasetHandle dataset, const void* data, int data_type, int32_t nrow, int32_t ncol, int32_t start_row) { return FLC_DatasetPushRows(dataset, data, data_type, nrow, ncol, start_row); }
inline int LGBM_DatasetPushRowsWithMetadata(DatasetHandle dataset, const void* data, int data_type, int32_t nrow, int32_t ncol, int32_t start_row, const float* label, const float* weight, const double* init_score, const int32_t* query, int32_t tid) { return FLC_DatasetPushRowsWithMetadata(dataset, data, data_type, nrow, ncol, start_row, label, weight, init_score, query, tid); }
inline int LGBM_DatasetPushRowsByCSR(DatasetHandle dataset, const void* indptr, int indptr_type, const int32_t* indices, const void* data, int data_type, int64_t nindptr, int64_t nelem, int64_t num_col, int64_t start_row) { return FLC_DatasetPushRowsByCSR(dataset, indptr, indptr_type, indices, data, data_type, nindptr, nelem, num_col, start_row); }
inline int LGBM_DatasetPushRowsByCSRWithMetadata(DatasetHandle dataset, const void* indptr, int indptr_type, const int32_t* indices, const void* data, int data_type, int64_t nindptr, int64_t nelem, int64_t start_row, const float* label, const float* weight, const double* init_score, const int32_t* query, int32_t tid) { return FLC_DatasetPushRowsByCSRWithMetadata(dataset, indptr, indptr_type, indices, data, data_type, nindptr, nelem, start_row, label, weight, init_score, query, tid); }
inline int LGBM_DatasetSetWaitForManualFinish(DatasetHandle dataset, int wait) { return FLC_DatasetSetWaitForManualFinish(dataset, wait); }
inline int LGBM_DatasetMarkFinished(DatasetHandle dataset) { return FLC_DatasetMarkFinished(dataset); }
inline int LGBM_DatasetCreateFromCSR(const void* indptr, int indptr_type, const int32_t* indices, const void* data, int data_type, int64_t nindptr, int64_t nelem, int64_t num_col, const char* parameters, const DatasetHandle reference, DatasetHandle* out) { return FLC_DatasetCreateFromCSR(indptr, indptr_type, indices, data, data_type, nindptr, nelem, num_col, parameters, reference, out); }
inline int LGBM_DatasetCreateFromCSRFunc(void* get_row_funptr, int num_rows, int64_t num_col, const char* parameters, const DatasetHandle reference, DatasetHandle* out) { return FLC_DatasetCreateFromCSRFunc(get_row_funptr, num_rows, num_col, parameters, reference, out); }
inline int LGBM_DatasetCreateFromCSC(const void* col_ptr, int col_ptr_type, const int32_t* indices, const void* data, int data_type, int64_t ncol_ptr, int64_t nelem, int64_t num_row, const char* parameters, const DatasetHandle reference, DatasetHandle* out) { return FLC_DatasetCreateFromCSC(col_ptr, col_ptr_type, indices, data, data_type, ncol_ptr, nelem, num_row, parameters, reference, out); }
inline int LGBM_DatasetCreateFromMat(const void* data, int data_type, int32_t nrow, int32_t ncol, int is_row_major, const char* parameters, const DatasetHandle reference, DatasetHandle* out) { return FLC_DatasetCreateFromMat(data, data_type, nrow, ncol, is_row_major, parameters, reference, out); }
inline int LGBM_DatasetCreateFromMatDevice(const void* data, int data_type, int32_t nrow, int32_t ncol, int is_row_major, const char* parameters, const DatasetHandle reference, DatasetHandle* out) { return FLC_DatasetCreateFromMatDevice(data, data_type, nrow, ncol, is_row_major, parameters, reference, out); }
inline int LGBM_DatasetCreateFromMats(int32_t nmat, const void** data, int data_type, int32_t* nrow, int32_t ncol, int* is_row_major, const char* parameters, const DatasetHandle reference, DatasetHandle* out) { return FLC_DatasetCreateFromMats(nmat, data, data_type, nrow, ncol, is_row_major, parameters, reference, out); }
inline int LGBM_DatasetCreateFromArrowStream(struct ArrowArrayStream* stream, const char* parameters, const DatasetHandle reference, DatasetHandle *out) { return FLC_DatasetCreateFromArrowStream(stream, parameters, reference, out); }
inline int LGBM_DatasetGetSubset(const DatasetHandle handle, const int32_t* used_row_indices, int32_t num_used_row_indices, const char* parameters, DatasetHandle* out) { return FLC_DatasetGetSubset(handle, used_row_indices, num_used_row_indices, parameters, out); }
inline int LGBM_DatasetSetFeatureNames(DatasetHandle handle, const char** feature_names, int num_feature_names) { return FLC_DatasetSetFeatureNames(handle, feature_names, num_feature_names); }
inline int LGBM_DatasetGetFeatureNames(DatasetHandle handle, const int len, int* num_feature_names, const size_t buffer_len, size_t* out_buffer_len, char** feature_names) { return FLC_DatasetGetFeatureNames(handle, len, num_feature_names, buffer_len, out_buffer_len, feature_names); }
inline int LGBM_DatasetFree(DatasetHandle handle) { return FLC_DatasetFree(handle); }
inline int LGBM_DatasetSaveBinary(DatasetHandle handle, const char* filename) { return FLC_DatasetSaveBinary(handle, filename); }
inline int LGBM_DatasetSerializeReferenceToBinary(DatasetHandle handle, ByteBufferHandle* out, int32_t* out_len) { return FLC_DatasetSerializeReferenceToBinary(handle, out, out_len); }
inline int LGBM_DatasetDumpText(DatasetHandle handle, const char* filename) { return FLC_DatasetDumpText(handle, filename); }
inline int LGBM_DatasetSetField(DatasetHandle handle, const char* field_name, const void* field_data, int num_element, int type) { return FLC_DatasetSetField(handle, field_name, field_data, num_element, type); }
inline int LGBM_DatasetSetFieldFromArrowStream(DatasetHandle handle, const char* field_name, struct ArrowArrayStream* stream) { return FLC_DatasetSetFieldFromArrowStream(handle, field_name, stream); }
inline int LGBM_DatasetGetField(DatasetHandle handle, const char* field_name, int* out_len, const void** out_ptr, int* out_type) { return FLC_DatasetGetField(handle, field_name, out_len, out_ptr, out_type); }
inline int LGBM_DatasetUpdateParamChecking(const char* old_parameters, const char* new_parameters) { return FLC_DatasetUpdateParamChecking(old_parameters, new_parameters); }
inline int LGBM_DatasetGetNumData(DatasetHandle handle, int* out) { return FLC_DatasetGetNumData(handle, out); }
inline int LGBM_DatasetGetNumFeature(DatasetHandle handle, int* out) { return FLC_DatasetGetNumFeature(handle, out); }
inline int LGBM_DatasetGetFeatureNumBin(DatasetHandle handle, int feature, int* out) { return FLC_DatasetGetFeatureNumBin(handle, feature, out); }
inline int LGBM_DatasetAddFeaturesFrom(DatasetHandle target, DatasetHandle source) { return FLC_DatasetAddFeaturesFrom(target, source); }
inline int LGBM_BoosterGetLinear(BoosterHandle handle, int* out) { return FLC_BoosterGetLinear(handle, out); }
inline int LGBM_BoosterCreate(const DatasetHandle train_data, const char* parameters, BoosterHandle* out) { return FLC_BoosterCreate(train_data, parameters, out); }
inline int LGBM_BoosterCreateFromModelfile(const char* filename, int* out_num_iterations, BoosterHandle* out) { return FLC_BoosterCreateFromModelfile(filename, out_num_iterations, out); }
inline int LGBM_BoosterLoadModelFromString(const char* model_str, int* out_num_iterations, BoosterHandle* out) { return FLC_BoosterLoadModelFromString(model_str, out_num_iterations, out); }
inline int LGBM_BoosterGetLoadedParam(BoosterHandle handle, int64_t buffer_len, int64_t* out_len, char* out_str) { return FLC_BoosterGetLoadedParam(handle, buffer_len, out_len, out_str); }
inline int LGBM_BoosterFree(BoosterHandle handle) { return FLC_BoosterFree(handle); }
inline int LGBM_BoosterShuffleModels(BoosterHandle handle, int start_iter, int end_iter) { return FLC_BoosterShuffleModels(handle, start_iter, end_iter); }
inline int LGBM_BoosterMerge(BoosterHandle handle, BoosterHandle other_handle) { return FLC_BoosterMerge(handle, other_handle); }
inline int LGBM_BoosterAddValidData(BoosterHandle handle, const DatasetHandle valid_data) { return FLC_BoosterAddValidData(handle, valid_data); }
inline int LGBM_BoosterResetTrainingData(BoosterHandle handle, const DatasetHandle train_data) { return FLC_BoosterResetTrainingData(handle, train_data); }
inline int LGBM_BoosterResetParameter(BoosterHandle handle, const char* parameters) { return FLC_BoosterResetParameter(handle, parameters); }
inline int LGBM_BoosterGetNumClasses(BoosterHandle handle, int* out_len) { return FLC_BoosterGetNumClasses(handle, out_len); }
inline int LGBM_BoosterUpdateOneIter(BoosterHandle handle, int* produced_empty_tree) { return FLC_BoosterUpdateOneIter(handle, produced_empty_tree); }
inline int LGBM_BoosterRefit(BoosterHandle handle, const int32_t* leaf_preds, int32_t nrow, int32_t ncol) { return FLC_BoosterRefit(handle, leaf_preds, nrow, ncol); }
inline int LGBM_BoosterUpdateOneIterCustom(BoosterHandle handle, const float* grad, const float* hess, int* produced_empty_tree) { return FLC_BoosterUpdateOneIterCustom(handle, grad, hess, produced_empty_tree); }
inline int LGBM_BoosterRollbackOneIter(BoosterHandle handle) { return FLC_BoosterRollbackOneIter(handle); }
inline int LGBM_BoosterGetCurrentIteration(BoosterHandle handle, int* out_iteration) { return FLC_BoosterGetCurrentIteration(handle, out_iteration); }
inline int LGBM_BoosterNumModelPerIteration(BoosterHandle handle, int* out_tree_per_iteration) { return FLC_BoosterNumModelPerIteration(handle, out_tree_per_iteration); }
inline int LGBM_BoosterNumberOfTotalModel(BoosterHandle handle, int* out_models) { return FLC_BoosterNumberOfTotalModel(handle, out_models); }
inline int LGBM_BoosterGetEvalCounts(BoosterHandle handle, int* out_len) { return FLC_BoosterGetEvalCounts(handle, out_len); }
inline int LGBM_BoosterGetEvalNames(BoosterHandle handle, const int len, int* out_len, const size_t buffer_len, size_t* out_buffer_len, char** out_strs) { return FLC_BoosterGetEvalNames(handle, len, out_len, buffer_len, out_buffer_len, out_strs); }
inline int LGBM_BoosterGetFeatureNames(BoosterHandle handle, const int len, int* out_len, const size_t buffer_len, size_t* out_buffer_len, char** out_strs) { return FLC_BoosterGetFeatureNames(handle, len, out_len, buffer_len, out_buffer_len, out_strs); }
inline int LGBM_BoosterValidateFeatureNames(BoosterHandle handle, const char** data_names, int data_num_features) { return FLC_BoosterValidateFeatureNames(handle, data_names, data_num_features); }
inline int LGBM_BoosterGetNumFeature(BoosterHandle handle, int* out_len) { return FLC_BoosterGetNumFeature(handle, out_len); }
inline int LGBM_BoosterGetEval(BoosterHandle handle, int data_idx, int* out_len, double* out_results) { return FLC_BoosterGetEval(handle, data_idx, out_len, out_results); }
inline int LGBM_BoosterGetNumPredict(BoosterHandle handle, int data_idx, int64_t* out_len) { return FLC_BoosterGetNumPredict(handle, data_idx, out_len); }
inline int LGBM_BoosterGetPredict(BoosterHandle handle, int data_idx, int64_t* out_len, double* out_result) { return FLC_BoosterGetPredict(handle, data_idx, out_len, out_result); }
inline int LGBM_BoosterPredictForFile(BoosterHandle handle, const char* data_filename, int data_has_header, int predict_type, int start_iteration, int num_iteration, const char* parameter, const char* result_filename) { return FLC_BoosterPredictForFile(handle, data_filename, data_has_header, predict_type, start_iteration, num_iteration, parameter, result_filename); }
inline int LGBM_BoosterCalcNumPredict(BoosterHandle handle, int num_row, int predict_type, int start_iteration, int num_iteration, int64_t* out_len) { return FLC_BoosterCalcNumPredict(handle, num_row, predict_type, start_iteration, num_iteration, out_len); }
inline int LGBM_FastConfigFree(FastConfigHandle fastConfig) { return FLC_FastConfigFree(fastConfig); }
inline int LGBM_BoosterPredictForCSR(BoosterHandle handle, const void* indptr, int indptr_type, const int32_t* indices, const void* data, int data_type, int64_t nindptr, int64_t nelem, int64_t num_col, int predict_type, int start_iteration, int num_iteration, const char* parameter, int64_t* out_len, double* out_result) { return FLC_BoosterPredictForCSR(handle, indptr, indptr_type, indices, data, data_type, nindptr, nelem, num_col, predict_type, start_iteration, num_iteration, parameter, out_len, out_result); }
inline int LGBM_BoosterPredictSparseOutput(BoosterHandle handle, const void* indptr, int indptr_type, const int32_t* indices, const void* data, int data_type, int64_t nindptr, int64_t nelem, int64_t num_col_or_row, int predict_type, int start_iteration, int num_iteration, const char* parameter, int matrix_type, int64_t* out_len, void** out_indptr, int32_t** out_indices, void** out_data) { return FLC_BoosterPredictSparseOutput(handle, indptr, indptr_type, indices, data, data_type, nindptr, nelem, num_col_or_row, predict_type, start_iteration, num_iteration, parameter, matrix_type, out_len, out_indptr, out_indices, out_data); }
inline int LGBM_BoosterFreePredictSparse(void* indptr, int32_t* indices, void* data, int indptr_type, int data_type) { return FLC_BoosterFreePredictSparse(indptr, indices, data, indptr_type, data_type); }
inline int LGBM_BoosterPredictForCSRSingleRow(BoosterHandle handle, const void* indptr, int indptr_type, const int32_t* indices, const void* data, int data_type, int64_t nindptr, int64_t nelem, int64_t num_col, int predict_type, int start_iteration, int num_iteration, const char* parameter, int64_t* out_len, double* out_result) { return FLC_BoosterPredictForCSRSingleRow(handle, indptr, indptr_type, indices, data, data_type, nindptr, nelem, num_col, predict_type, start_iteration, num_iteration, parameter, out_len, out_result); }
inline int LGBM_BoosterPredictForCSRSingleRowFastInit(BoosterHandle handle, const int predict_type, const int start_iteration, const int num_iteration, const int data_type, const int64_t num_col, const char* parameter, FastConfigHandle *out_fastConfig) { return FLC_BoosterPredictForCSRSingleRowFastInit(handle, predict_type, start_iteration, num_iteration, data_type, num_col, parameter, out_fastConfig); }
inline int LGBM_BoosterPredictForCSRSingleRowFast(FastConfigHandle fastConfig_handle, const void* indptr, const int indptr_type, const int32_t* indices, const void* data, const int64_t nindptr, const int64_t nelem, int64_t* out_len, double* out_result) { return FLC_BoosterPredictForCSRSingleRowFast(fastConfig_handle, indptr, indptr_type, indices, data, nindptr, nelem, out_len, out_result); }
inline int LGBM_BoosterPredictForCSC(BoosterHandle handle, const void* col_ptr, int col_ptr_type, const int32_t* indices, const void* data, int data_type, int64_t ncol_ptr, int64_t nelem, int64_t num_row, int predict_type, int start_iteration, int num_iteration, const char* parameter, int64_t* out_len, double* out_result) { return FLC_BoosterPredictForCSC(handle, col_ptr, col_ptr_type, indices, data, data_type, ncol_ptr, nelem, num_row, predict_type, start_iteration, num_iteration, parameter, out_len, out_result); }
inline int LGBM_BoosterPredictForMat(BoosterHandle handle, const void* data, int data_type, int32_t nrow, int32_t ncol, int is_row_major, int predict_type, int start_iteration, int num_iteration, const char* parameter, int64_t* out_len, double* out_result) { return FLC_BoosterPredictForMat(handle, data, data_type, nrow, ncol, is_row_major, predict_type, start_iteration, num_iteration, parameter, out_len, out_result); }
inline int LGBM_BoosterPredictForMatSingleRow(BoosterHandle handle, const void* data, int data_type, int ncol, int is_row_major, int predict_type, int start_iteration, int num_iteration, const char* parameter, int64_t* out_len, double* out_result) { return FLC_BoosterPredictForMatSingleRow(handle, data, data_type, ncol, is_row_major, predict_type, start_iteration, num_iteration, parameter, out_len, out_result); }
inline int LGBM_BoosterPredictForMatSingleRowFastInit(BoosterHandle handle, const int predict_type, const int start_iteration, const int num_iteration, const int data_type, const int32_t ncol, const char* parameter, FastConfigHandle *out_fastConfig) { return FLC_BoosterPredictForMatSingleRowFastInit(handle, predict_type, start_iteration, num_iteration, data_type, ncol, parameter, out_fastConfig); }
inline int LGBM_BoosterPredictForMatSingleRowFast(FastConfigHandle fastConfig_handle, const void* data, int64_t* out_len, double* out_result) { return FLC_BoosterPredictForMatSingleRowFast(fastConfig_handle, data, out_len, out_result); }
inline int LGBM_BoosterPredictForMats(BoosterHandle handle, const void** data, int data_type, int32_t nrow, int32_t ncol, int predict_type, int start_iteration, int num_iteration, const char* parameter, int64_t* out_len, double* out_result) { return FLC_BoosterPredictForMats(handle, data, data_type, nrow, ncol, predict_type, start_iteration, num_iteration, parameter, out_len, out_result); }
inline int LGBM_BoosterPredictForArrowStream(BoosterHandle handle, struct ArrowArrayStream* stream, int predict_type, int start_iteration, int num_iteration, const char* parameter, int64_t* out_len, double* out_result) { return FLC_BoosterPredictForArrowStream(handle, stream, predict_type, start_iteration, num_iteration, parameter, out_len, out_result); }
inline int LGBM_BoosterSaveModel(BoosterHandle handle, int start_iteration, int num_iteration, int feature_importance_type, const char* filename) { return FLC_BoosterSaveModel(handle, start_iteration, num_iteration, feature_importance_type, filename); }
inline int LGBM_BoosterSaveModelToString(BoosterHandle handle, int start_iteration, int num_iteration, int feature_importance_type, int64_t buffer_len, int64_t* out_len, char* out_str) { return FLC_BoosterSaveModelToString(handle, start_iteration, num_iteration, feature_importance_type, buffer_len, out_len, out_str); }
inline int LGBM_BoosterDumpModel(BoosterHandle handle, int start_iteration, int num_iteration, int feature_importance_type, int64_t buffer_len, int64_t* out_len, char* out_str) { return FLC_BoosterDumpModel(handle, start_iteration, num_iteration, feature_importance_type, buffer_len, out_len, out_str); }
inline int LGBM_BoosterGetLeafValue(BoosterHandle handle, int tree_idx, int leaf_idx, double* out_val) { return FLC_BoosterGetLeafValue(handle, tree_idx, leaf_idx, out_val); }
inline int LGBM_BoosterSetLeafValue(BoosterHandle handle, int tree_idx, int leaf_idx, double val) { return FLC_BoosterSetLeafValue(handle, tree_idx, leaf_idx, val); }
inline int LGBM_BoosterFeatureImportance(BoosterHandle handle, int num_iteration, int importance_type, double* out_results) { return FLC_BoosterFeatureImportance(handle, num_iteration, importance_type, out_results); }
inline int LGBM_BoosterGetUpperBoundValue(BoosterHandle handle, double* out_results) { return FLC_BoosterGetUpperBoundValue(handle, out_results); }
inline int LGBM_BoosterGetLowerBoundValue(BoosterHandle handle, double* out_results) { return FLC_BoosterGetLowerBoundValue(handle, out_results); }
inline int LGBM_NetworkInit(const char* machines, int local_listen_port, int listen_time_out, int num_machines) { return FLC_NetworkInit(machines, local_listen_port, listen_time_out, num_machines); }
inline int LGBM_NetworkFree() { return FLC_NetworkFree(); }
inline int LGBM_NetworkInitWithFunctions(int num_machines, int rank, void* reduce_scatter_ext_fun, void* allgather_ext_fun) { return FLC_NetworkInitWithFunctions(num_machines, rank, reduce_scatter_ext_fun, allgather_ext_fun); }
inline int LGBM_SetMaxThreads(int num_threads) { return FLC_SetMaxThreads(num_threads); }
inline int LGBM_GetMaxThreads(int* out) { return FLC_GetMaxThreads(out); }

#endif  /* FALCATA_C_API_COMPAT_H_ */
